'use client';
import { FormEvent, useEffect, useState } from 'react';
import Link from 'next/link';
import { Alert, Button, Card, Group, Loader, Select, Stack, Switch, Text, TextInput, Textarea, Title } from '@mantine/core';
import { IconArrowLeft, IconDeviceFloppy, IconPlus, IconStar, IconTrash } from '@tabler/icons-react';

type Asset = { id: string; url: string; type: 'image' | 'video' | 'file'; is_cover?: boolean };
type News = { id: string; title: string; description: string; is_published: boolean; assets?: Asset[] };
const dataOf = <T,>(value: unknown) => ((value as { data?: T })?.data ?? value) as T;
export function NewsEditor({ newsId }: { newsId: string }) {
  const [news, setNews] = useState<News | null>(null); const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [published, setPublished] = useState(false); const [assetUrl, setAssetUrl] = useState(''); const [assetType, setAssetType] = useState<'image' | 'video' | 'file'>('image'); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const load = async () => { setLoading(true); try { const r = await fetch(`/api/eo/eo/news/${newsId}`); const x = await r.json(); if (!r.ok) throw new Error(x.error || 'Berita tidak ditemukan.'); const item = dataOf<News>(x); setNews(item); setTitle(item.title); setDescription(item.description); setPublished(item.is_published); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Berita gagal dimuat.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [newsId]);
  const save = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(null); const r = await fetch(`/api/eo/eo/news/${newsId}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ title, description, is_published: published }) }); const x = await r.json(); if (!r.ok) setError(x.error || x.message || 'Berita gagal disimpan.'); else { setNotice('Berita berhasil disimpan.'); load(); } setSaving(false); };
  const addAsset = async () => { if (!assetUrl) return; const r = await fetch(`/api/eo/eo/news/${newsId}/assets`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ url: assetUrl, type: assetType, is_cover: !(news?.assets?.length) }) }); const x = await r.json(); if (!r.ok) setError(x.error || 'Asset gagal ditambahkan.'); else { setAssetUrl(''); load(); } };
  const updateAsset = async (assetId: string, is_cover: boolean) => { const r = await fetch(`/api/eo/eo/news/${newsId}/assets/${assetId}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ is_cover }) }); if (!r.ok) setError('Cover berita gagal diperbarui.'); else load(); };
  const removeAsset = async (assetId: string) => { if (!confirm('Hapus asset ini?')) return; const r = await fetch(`/api/eo/eo/news/${newsId}/assets/${assetId}`, { method: 'DELETE' }); if (!r.ok) setError('Asset gagal dihapus.'); else load(); };
  if (loading) return <Loader />; if (!news) return <Alert color="red">{error || 'Berita tidak ditemukan.'}</Alert>;
  return <Stack><Button component={Link} href="/eo/news" variant="subtle" px={0} leftSection={<IconArrowLeft size={16} />}>Kembali ke berita</Button><Title order={1}>Edit berita</Title>{error && <Alert color="red">{error}</Alert>}{notice && <Alert color="green">{notice}</Alert>}<Card withBorder><form onSubmit={save}><Stack><TextInput label="Judul" value={title} onChange={x => setTitle(x.currentTarget.value)} required /><Textarea label="Isi berita" value={description} onChange={x => setDescription(x.currentTarget.value)} minRows={6} required /><Switch label="Publikasikan berita" checked={published} onChange={x => setPublished(x.currentTarget.checked)} /><Button type="submit" loading={saving} leftSection={<IconDeviceFloppy size={17} />}>Simpan berita</Button></Stack></form></Card><Title order={3}>Asset berita</Title><Card withBorder><Stack><Group grow><TextInput label="URL asset" value={assetUrl} onChange={x => setAssetUrl(x.currentTarget.value)} placeholder="https://..." /><Select label="Tipe" value={assetType} onChange={x => setAssetType((x || 'image') as typeof assetType)} data={['image', 'video', 'file']} /></Group><Button onClick={addAsset} leftSection={<IconPlus size={17} />} ml="auto">Tambah asset</Button></Stack></Card>{news.assets?.map(asset => <Card withBorder key={asset.id}><Group justify="space-between"><div><Text fw={600}>{asset.type}</Text><Text c="dimmed" size="sm" lineClamp={1}>{asset.url}</Text></div><Group><Button size="xs" variant={asset.is_cover ? 'filled' : 'light'} leftSection={<IconStar size={14} />} onClick={() => updateAsset(asset.id, true)}>{asset.is_cover ? 'Cover' : 'Jadikan cover'}</Button><Button size="xs" color="red" variant="subtle" onClick={() => removeAsset(asset.id)}><IconTrash size={16} /></Button></Group></Group></Card>)}</Stack>;
}
