'use client';
import { useEffect, useState } from 'react';
import { Alert, Button, FileInput, Group, Loader, Select, Stack, TextInput, Textarea, Title } from '@mantine/core';
import { IconAlertCircle, IconDeviceFloppy, IconUpload } from '@tabler/icons-react';

type Profile = { name?: string; email?: string; phone?: string; description?: string; website?: string; country?: string; state?: string; city?: string; bank_account_holder_name?: string; bank_code?: string; bank_account_number?: string; logo_url?: string };
export function OrganizationSettings() {
 const [data,setData]=useState<Profile>({});const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState<string|null>(null);const [notice,setNotice]=useState<string|null>(null);
 useEffect(()=>{fetch('/api/eo/auth/profile').then(async r=>{const x=await r.json();if(!r.ok)throw new Error(x.error||'Profil gagal dimuat.');setData(x.data??x)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 const update=(key:keyof Profile,value:string)=>setData(x=>({...x,[key]:value}));
 const save=async()=>{setSaving(true);setError(null);try{const r=await fetch('/api/eo/auth/organization-settings',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const x=await r.json();if(!r.ok)throw new Error(x.error||x.message||'Pengaturan gagal disimpan.');setNotice('Pengaturan organisasi berhasil disimpan.')}catch(e){setError(e instanceof Error?e.message:'Pengaturan gagal disimpan.')}finally{setSaving(false)}};
 const upload=async(file:File|null)=>{if(!file)return;const form=new FormData();form.append('logo',file);const r=await fetch('/api/eo/auth/logo',{method:'PATCH',body:form});const x=await r.json();if(!r.ok)return setError(x.error||'Logo gagal diunggah.');setData(d=>({...d,logo_url:x.data?.logo_url??x.logo_url}));setNotice('Logo berhasil diperbarui.');};
 if(loading)return <Loader/>;return <Stack><Title order={1}>Pengaturan organisasi</Title>{error&&<Alert color="red" icon={<IconAlertCircle size={18}/>}>{error}</Alert>}{notice&&<Alert color="green">{notice}</Alert>}<FileInput label="Logo organisasi" placeholder={data.logo_url?'Logo tersedia, pilih untuk mengganti':'Pilih logo'} accept="image/png,image/jpeg" leftSection={<IconUpload size={16}/>} onChange={upload}/><Group grow><TextInput label="Nama organisasi" value={data.name||''} onChange={e=>update('name',e.currentTarget.value)}/><TextInput label="Email" type="email" value={data.email||''} onChange={e=>update('email',e.currentTarget.value)}/></Group><Group grow><TextInput label="Telepon" value={data.phone||''} onChange={e=>update('phone',e.currentTarget.value)}/><TextInput label="Website" value={data.website||''} onChange={e=>update('website',e.currentTarget.value)}/></Group><Textarea label="Deskripsi" value={data.description||''} onChange={e=>update('description',e.currentTarget.value)} minRows={3}/><Group grow><TextInput label="Negara" value={data.country||''} onChange={e=>update('country',e.currentTarget.value)}/><TextInput label="Provinsi" value={data.state||''} onChange={e=>update('state',e.currentTarget.value)}/><TextInput label="Kota" value={data.city||''} onChange={e=>update('city',e.currentTarget.value)}/></Group><Title order={3} mt="md">Rekening bank</Title><Group grow><TextInput label="Nama pemilik rekening" value={data.bank_account_holder_name||''} onChange={e=>update('bank_account_holder_name',e.currentTarget.value)}/><TextInput label="Kode bank" value={data.bank_code||''} onChange={e=>update('bank_code',e.currentTarget.value)}/><TextInput label="Nomor rekening" value={data.bank_account_number||''} onChange={e=>update('bank_account_number',e.currentTarget.value)}/></Group><Button leftSection={<IconDeviceFloppy size={17}/>} onClick={save} loading={saving} ml="auto">Simpan pengaturan</Button></Stack>;
}
