'use client';

import { FormEvent, useState } from 'react';
import Link from 'next/link';
import { Alert, Button, Paper, PasswordInput, Stack, Text, TextInput, Title } from '@mantine/core';

export function RegisterOrganization() {
  const [form, setForm] = useState({ name: '', email: '', password: '', description: '', phone: '', package: 'standard' });
  const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false);
  const update = (key: keyof typeof form, value: string) => setForm(x => ({ ...x, [key]: value }));
  const submit = async (event: FormEvent) => { event.preventDefault(); setLoading(true); setError(null); try { const r = await fetch('/api/eo-public/auth/register', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const x = await r.json(); if (!r.ok) throw new Error(x.error || x.message || 'Registrasi gagal.'); setMessage('Registrasi organisasi berhasil. Silakan lanjutkan sesuai instruksi yang dikirimkan.'); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Registrasi gagal.'); } finally { setLoading(false); } };
  return <Paper withBorder p="xl" radius="lg"><form onSubmit={submit}><Stack><Title order={1}>Daftar Event Organizer</Title>{error && <Alert color="red">{error}</Alert>}{message && <Alert color="green">{message}</Alert>}<TextInput label="Nama organisasi" value={form.name} onChange={e => update('name', e.currentTarget.value)} required /><TextInput label="Email" type="email" value={form.email} onChange={e => update('email', e.currentTarget.value)} required /><TextInput label="Telepon" value={form.phone} onChange={e => update('phone', e.currentTarget.value)} required /><TextInput label="Deskripsi organisasi" value={form.description} onChange={e => update('description', e.currentTarget.value)} required /><TextInput label="Paket" value={form.package} onChange={e => update('package', e.currentTarget.value)} required /><PasswordInput label="Password" value={form.password} onChange={e => update('password', e.currentTarget.value)} required /><Button type="submit" loading={loading}>Daftar organisasi</Button><Text size="sm">Sudah punya akun? <Text component={Link} href="/eo/login" span c="blue">Masuk</Text></Text></Stack></form></Paper>;
}

export function ForgotPassword() {
  const [email, setEmail] = useState(''); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setLoading(true); setError(null); try { const r = await fetch('/api/eo-public/auth/forgot-password', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email }) }); const x = await r.json(); if (!r.ok) throw new Error(x.error || x.message || 'Permintaan gagal.'); setMessage('Jika email terdaftar, tautan reset password telah dikirim.'); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Permintaan gagal.'); } finally { setLoading(false); } };
  return <Paper withBorder p="xl" radius="lg"><form onSubmit={submit}><Stack><Title order={1}>Lupa password</Title><Text c="dimmed">Masukkan email akun Event Organizer Anda.</Text>{error && <Alert color="red">{error}</Alert>}{message && <Alert color="green">{message}</Alert>}<TextInput label="Email" type="email" value={email} onChange={e => setEmail(e.currentTarget.value)} required /><Button type="submit" loading={loading}>Kirim tautan reset</Button><Text component={Link} href="/eo/login" size="sm" c="blue">Kembali ke login</Text></Stack></form></Paper>;
}

export function ResetPassword() {
  const [password, setPassword] = useState(''); const [confirmPassword, setConfirmPassword] = useState(''); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (password !== confirmPassword) return setError('Konfirmasi password tidak sama.'); if (!/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&]).{8,}$/.test(password)) return setError('Password minimal 8 karakter dan harus memuat huruf besar, huruf kecil, angka, serta karakter @$!%*?&.'); const token = new URLSearchParams(window.location.search).get('token'); if (!token) return setError('Token reset password tidak tersedia.'); setLoading(true); setError(null); try { const check = await fetch('/api/eo-public/auth/validate-reset-token', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ token }) }); if (!check.ok) throw new Error('Token reset password tidak valid atau telah kedaluwarsa.'); const response = await fetch('/api/eo-public/auth/reset-password', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ token, new_password: password, confirm_password: confirmPassword }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || data.message || 'Password gagal diperbarui.'); setMessage('Password berhasil diperbarui. Anda dapat masuk menggunakan password baru.'); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Password gagal diperbarui.'); } finally { setLoading(false); } };
  return <Paper withBorder p="xl" radius="lg"><form onSubmit={submit}><Stack><Title order={1}>Buat password baru</Title>{error && <Alert color="red">{error}</Alert>}{message && <Alert color="green">{message}</Alert>}<PasswordInput label="Password baru" value={password} onChange={e => setPassword(e.currentTarget.value)} required /><PasswordInput label="Konfirmasi password baru" value={confirmPassword} onChange={e => setConfirmPassword(e.currentTarget.value)} required /><Button type="submit" loading={loading}>Simpan password baru</Button><Text component={Link} href="/eo/login" size="sm" c="blue">Kembali ke login</Text></Stack></form></Paper>;
}
