'use client';

import { FormEvent, useEffect, useState } from 'react';
import Link from 'next/link';
import { Alert, Button, Card, Checkbox, Divider, Group, Loader, Modal, NumberInput, Select, Stack, Switch, Text, TextInput, Textarea, Title } from '@mantine/core';
import { useDisclosure } from '@mantine/hooks';
import { IconAlertCircle, IconArrowLeft, IconPlus, IconTrash } from '@tabler/icons-react';

type Ticket = { id: string; name: string; description?: string; normal_price?: number; price_cents: number; quantity: number; quantity_sold?: number; sale_start?: string; sale_end?: string; is_active: boolean; variant?: string; min_per_order?: number; max_per_order?: number; sort_order?: number; bonus_threshold?: number; bonus_quantity?: number };
type Addition = { id: string; name: string; race_date?: string; location?: string };
type Addon = { id: string; name: string; description?: string; price: number; max_quantity?: number; image_url?: string; sort_order?: number; is_active: boolean };
const dataOf = <T,>(payload: unknown): T => ((payload as { data?: T })?.data ?? payload) as T;

export function AdditionTickets({ eventId, additionId }: { eventId: string; additionId: string }) {
  const [addition, setAddition] = useState<Addition | null>(null);
  const [tickets, setTickets] = useState<Ticket[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [opened, modal] = useDisclosure(false);
  const [editing, setEditing] = useState<Ticket | null>(null);
  const load = async () => {
    setLoading(true); setError(null);
    try {
      const [additionResponse, ticketResponse] = await Promise.all([fetch(`/api/eo/additions/${additionId}`), fetch(`/api/eo/ticket-types?addition_id=${additionId}`)]);
      const additionPayload = await additionResponse.json();
      const ticketPayload = await ticketResponse.json();
      if (!additionResponse.ok || !ticketResponse.ok) throw new Error(additionPayload.error || ticketPayload.error || 'Data edisi gagal dimuat.');
      setAddition(dataOf<Addition>(additionPayload)); setTickets(dataOf<Ticket[]>(ticketPayload) || []);
    } catch (cause) { setError(cause instanceof Error ? cause.message : 'Data edisi gagal dimuat.'); }
    finally { setLoading(false); }
  };
  useEffect(() => { load(); }, [additionId]);
  const remove = async (ticket: Ticket) => {
    if (!window.confirm(`Hapus tiket ${ticket.name}?`)) return;
    const response = await fetch(`/api/eo/ticket-types/${ticket.id}`, { method: 'DELETE' });
    if (!response.ok) { setError('Tiket tidak dapat dihapus. Nonaktifkan tiket bila sudah memiliki peserta.'); return; }
    setTickets((current) => current.filter((item) => item.id !== ticket.id));
  };
  if (loading) return <Group justify="center" py="xl"><Loader /><Text c="dimmed">Memuat tiket...</Text></Group>;
  return <Stack gap="lg"><Button component={Link} href={`/eo/events/${eventId}`} variant="subtle" px={0} leftSection={<IconArrowLeft size={16} />}>Kembali ke event</Button>{error && <Alert color="red" icon={<IconAlertCircle size={18} />}>{error}</Alert>}<Group justify="space-between"><div><Title order={1}>{addition?.name || 'Edisi event'}</Title><Text c="dimmed">Kelola kategori tiket dan add-on.</Text></div><Button leftSection={<IconPlus size={17} />} onClick={() => { setEditing(null); modal.open(); }}>Tambah tiket</Button></Group><Stack>{tickets.map((ticket) => <Card key={ticket.id} withBorder radius="lg"><Group justify="space-between"><div><Text fw={700}>{ticket.name}</Text><Text size="sm" c="dimmed">Rp{ticket.price_cents.toLocaleString('id-ID')} · {ticket.quantity_sold || 0}/{ticket.quantity} terjual · {ticket.is_active ? 'Aktif' : 'Nonaktif'}</Text></div><Group><Button size="xs" variant="light" onClick={() => { setEditing(ticket); modal.open(); }}>Ubah</Button><Button component={Link} href={`/eo/events/${eventId}/additions/${additionId}/tickets/${ticket.id}`} size="xs" variant="subtle">Add-on</Button><Button size="xs" color="red" variant="subtle" onClick={() => remove(ticket)} aria-label="Hapus tiket"><IconTrash size={16} /></Button></Group></Group></Card>)}{!tickets.length && <Text c="dimmed" ta="center" py="xl">Belum ada tiket untuk edisi ini.</Text>}</Stack><TicketModal opened={opened} onClose={modal.close} ticket={editing} additionId={additionId} onSaved={load} /></Stack>;
}

function TicketModal({ opened, onClose, ticket, additionId, onSaved }: { opened: boolean; onClose: () => void; ticket: Ticket | null; additionId: string; onSaved: () => void }) {
  const [name, setName] = useState(''); const [description, setDescription] = useState(''); const [price, setPrice] = useState<number | ''>(''); const [normalPrice, setNormalPrice] = useState<number | ''>(''); const [quantity, setQuantity] = useState<number | ''>(''); const [minOrder, setMinOrder] = useState<number | ''>(1); const [maxOrder, setMaxOrder] = useState<number | ''>(4); const [sortOrder, setSortOrder] = useState<number | ''>(0); const [saleStart, setSaleStart] = useState(''); const [saleEnd, setSaleEnd] = useState(''); const [variant, setVariant] = useState<string>('regular'); const [bonusThreshold, setBonusThreshold] = useState<number | ''>(''); const [bonusQuantity, setBonusQuantity] = useState<number | ''>(''); const [active, setActive] = useState(true); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  useEffect(() => { setName(ticket?.name || ''); setDescription(ticket?.description || ''); setPrice(ticket?.price_cents || ''); setNormalPrice(ticket?.normal_price || ticket?.price_cents || ''); setQuantity(ticket?.quantity || ''); setMinOrder(ticket?.min_per_order || 1); setMaxOrder(ticket?.max_per_order || 4); setSortOrder(ticket?.sort_order || 0); setSaleStart(ticket?.sale_start ? new Date(ticket.sale_start).toISOString().slice(0, 16) : ''); setSaleEnd(ticket?.sale_end ? new Date(ticket.sale_end).toISOString().slice(0, 16) : ''); setVariant(ticket?.variant || 'regular'); setBonusThreshold(ticket?.bonus_threshold || ''); setBonusQuantity(ticket?.bonus_quantity || ''); setActive(ticket?.is_active ?? true); setError(null); }, [ticket, opened]);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!name || price === '' || quantity === '') return setError('Nama, harga, dan kuota wajib diisi.'); if (variant === 'community' && (Number(bonusThreshold) < 2 || Number(bonusQuantity) < 1 || Number(bonusQuantity) >= Number(bonusThreshold))) return setError('Tiket komunitas membutuhkan ambang bonus minimal 2 dan bonus lebih kecil dari ambang.'); setSaving(true); try { const payload = { name, description: description || undefined, price_cents: Number(price), normal_price: normalPrice === '' ? undefined : Number(normalPrice), quantity: Number(quantity), quantity_reserved: 0, sale_start: saleStart ? new Date(saleStart).toISOString() : undefined, sale_end: saleEnd ? new Date(saleEnd).toISOString() : undefined, min_per_order: Number(minOrder), max_per_order: Number(maxOrder), sort_order: Number(sortOrder), is_active: active, variant, bonus_threshold: variant === 'community' ? Number(bonusThreshold) : undefined, bonus_quantity: variant === 'community' ? Number(bonusQuantity) : undefined, ...(ticket ? {} : { addition_id: additionId }) }; const response = await fetch(ticket ? `/api/eo/ticket-types/${ticket.id}` : '/api/eo/ticket-types', { method: ticket ? 'PATCH' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || data.message || 'Tiket gagal disimpan.'); onClose(); onSaved(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Tiket gagal disimpan.'); } finally { setSaving(false); } };
  return <Modal opened={opened} onClose={onClose} title={ticket ? 'Ubah tiket' : 'Tambah tiket'} centered size="lg"><form onSubmit={submit}><Stack>{error && <Alert color="red">{error}</Alert>}<TextInput label="Nama tiket" value={name} onChange={(e) => setName(e.currentTarget.value)} required /><Textarea label="Deskripsi" value={description} onChange={(e) => setDescription(e.currentTarget.value)} /><Group grow><NumberInput label="Harga jual (Rp)" value={price} onChange={(value) => setPrice(typeof value === 'number' ? value : '')} min={0} required /><NumberInput label="Harga normal (Rp)" value={normalPrice} onChange={(value) => setNormalPrice(typeof value === 'number' ? value : '')} min={0} /></Group><Group grow><NumberInput label="Kuota" value={quantity} onChange={(value) => setQuantity(typeof value === 'number' ? value : '')} min={1} required /><NumberInput label="Urutan tampil" value={sortOrder} onChange={(value) => setSortOrder(typeof value === 'number' ? value : '')} min={0} /></Group><Group grow><NumberInput label="Minimum per pesanan" value={minOrder} onChange={(value) => setMinOrder(typeof value === 'number' ? value : '')} min={1} /><NumberInput label="Maksimum per pesanan" value={maxOrder} onChange={(value) => setMaxOrder(typeof value === 'number' ? value : '')} min={1} /></Group><Group grow><TextInput label="Mulai penjualan" type="datetime-local" value={saleStart} onChange={e => setSaleStart(e.currentTarget.value)} /><TextInput label="Akhir penjualan" type="datetime-local" value={saleEnd} onChange={e => setSaleEnd(e.currentTarget.value)} /></Group><Select label="Varian tiket" data={[{ value: 'regular', label: 'Reguler' }, { value: 'community', label: 'Komunitas' }]} value={variant} onChange={value => setVariant(value || 'regular')} />{variant === 'community' && <Group grow><NumberInput label="Ambang bonus" value={bonusThreshold} onChange={value => setBonusThreshold(typeof value === 'number' ? value : '')} min={2} /><NumberInput label="Jumlah bonus" value={bonusQuantity} onChange={value => setBonusQuantity(typeof value === 'number' ? value : '')} min={1} /></Group>}<Switch label="Tiket aktif" checked={active} onChange={(e) => setActive(e.currentTarget.checked)} /><Button type="submit" loading={saving}>Simpan tiket</Button></Stack></form></Modal>;
}

export function TicketAddons({ eventId, additionId, ticketId }: { eventId: string; additionId: string; ticketId: string }) {
  const [addons, setAddons] = useState<Addon[]>([]); const [name, setName] = useState(''); const [description, setDescription] = useState(''); const [price, setPrice] = useState<number | ''>(''); const [maxQuantity, setMaxQuantity] = useState<number | ''>(''); const [imageUrl, setImageUrl] = useState(''); const [editing, setEditing] = useState<Addon | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true);
  const load = async () => { const response = await fetch(`/api/eo/ticket-types/${ticketId}/addons`); const payload = await response.json(); if (response.ok) setAddons(dataOf<Addon[]>(payload) || []); else setError(payload.error || 'Add-on gagal dimuat.'); setLoading(false); };
  useEffect(() => { load(); }, [ticketId]);
  const add = async (event: FormEvent) => { event.preventDefault(); const response = await fetch(`/api/eo/ticket-types/${ticketId}/addons`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name, description: description || undefined, price: Number(price), max_quantity: maxQuantity === '' ? undefined : Number(maxQuantity), image_url: imageUrl || undefined, is_active: true, sort_order: 0 }) }); const payload = await response.json(); if (!response.ok) return setError(payload.error || 'Add-on gagal dibuat.'); setName(''); setDescription(''); setPrice(''); setMaxQuantity(''); setImageUrl(''); load(); };
  const remove = async (id: string) => { if (!confirm('Hapus add-on ini?')) return; const response = await fetch(`/api/eo/ticket-types/${ticketId}/addons/${id}`, { method: 'DELETE' }); if (!response.ok) return setError('Add-on tidak dapat dihapus. Nonaktifkan bila sudah dipilih peserta.'); load(); };
  if (loading) return <Loader />;
  return <Stack><Button component={Link} href={`/eo/events/${eventId}/additions/${additionId}`} variant="subtle" px={0} leftSection={<IconArrowLeft size={16} />}>Kembali ke tiket</Button><Title order={1}>Add-on tiket</Title>{error && <Alert color="red">{error}</Alert>}<Card withBorder><form onSubmit={add}><Stack><Group grow><TextInput label="Nama add-on" value={name} onChange={(e) => setName(e.currentTarget.value)} required /><NumberInput label="Harga (Rp)" value={price} onChange={(value) => setPrice(typeof value === 'number' ? value : '')} min={0} required /></Group><TextInput label="Deskripsi" value={description} onChange={e => setDescription(e.currentTarget.value)} /><Group grow><NumberInput label="Batas kuantitas" value={maxQuantity} onChange={value => setMaxQuantity(typeof value === 'number' ? value : '')} min={1} /><TextInput label="URL gambar" value={imageUrl} onChange={e => setImageUrl(e.currentTarget.value)} /></Group><Button type="submit" ml="auto">Tambah add-on</Button></Stack></form></Card>{addons.map((addon) => <Card key={addon.id} withBorder><Group justify="space-between"><div><Text fw={600}>{addon.name}</Text><Text size="sm" c="dimmed">Rp{addon.price.toLocaleString('id-ID')} {addon.max_quantity ? `· maksimal ${addon.max_quantity}` : ''}</Text></div><Group><Checkbox checked={addon.is_active} label="Aktif" onChange={async (e) => { await fetch(`/api/eo/ticket-types/${ticketId}/addons/${addon.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ is_active: e.currentTarget.checked }) }); load(); }} /><Button size="xs" variant="light" onClick={() => setEditing(addon)}>Ubah</Button><Button size="xs" color="red" variant="subtle" onClick={() => remove(addon.id)}><IconTrash size={16} /></Button></Group></Group></Card>)}<AddonModal addon={editing} ticketId={ticketId} onClose={() => setEditing(null)} onSaved={load} /></Stack>;
}

function AddonModal({ addon, ticketId, onClose, onSaved }: { addon: Addon | null; ticketId: string; onClose: () => void; onSaved: () => void }) {
  const [name, setName] = useState(''); const [description, setDescription] = useState(''); const [price, setPrice] = useState<number | ''>(''); const [maxQuantity, setMaxQuantity] = useState<number | ''>(''); const [imageUrl, setImageUrl] = useState(''); const [sortOrder, setSortOrder] = useState<number | ''>(0); const [active, setActive] = useState(true); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  useEffect(() => { setName(addon?.name || ''); setDescription(addon?.description || ''); setPrice(addon?.price ?? ''); setMaxQuantity(addon?.max_quantity ?? ''); setImageUrl(addon?.image_url || ''); setSortOrder(addon?.sort_order ?? 0); setActive(addon?.is_active ?? true); setError(null); }, [addon]);
  const save = async (event: FormEvent) => { event.preventDefault(); if (!addon) return; setSaving(true); try { const response = await fetch(`/api/eo/ticket-types/${ticketId}/addons/${addon.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name, description: description || undefined, price: Number(price), max_quantity: maxQuantity === '' ? undefined : Number(maxQuantity), image_url: imageUrl || undefined, sort_order: Number(sortOrder), is_active: active }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || payload.message || 'Add-on gagal diperbarui.'); onClose(); onSaved(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Add-on gagal diperbarui.'); } finally { setSaving(false); } };
  return <Modal opened={Boolean(addon)} onClose={onClose} title="Ubah add-on" centered><form onSubmit={save}><Stack>{error && <Alert color="red">{error}</Alert>}<TextInput label="Nama add-on" value={name} onChange={event => setName(event.currentTarget.value)} required /><Textarea label="Deskripsi" value={description} onChange={event => setDescription(event.currentTarget.value)} /><Group grow><NumberInput label="Harga (Rp)" value={price} onChange={value => setPrice(typeof value === 'number' ? value : '')} min={0} required /><NumberInput label="Batas kuantitas" value={maxQuantity} onChange={value => setMaxQuantity(typeof value === 'number' ? value : '')} min={1} /></Group><Group grow><TextInput label="URL gambar" value={imageUrl} onChange={event => setImageUrl(event.currentTarget.value)} /><NumberInput label="Urutan tampil" value={sortOrder} onChange={value => setSortOrder(typeof value === 'number' ? value : '')} min={0} /></Group><Switch label="Add-on aktif" checked={active} onChange={event => setActive(event.currentTarget.checked)} /><Button type="submit" loading={saving}>Simpan add-on</Button></Stack></form></Modal>;
}
